name: CLANG CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt install -y clang curl
    - name: get doctest.h
      run: curl https://raw.githubusercontent.com/onqtam/doctest/v2.4.9/doctest/doctest.h > doctest.h
    - name: get version
      run: clang++ -v
    - name: compile
      run: clang++ -o test_style test_style.cpp -std=c++17 -Wall -Wextra
    - name: compile
      run: clang++ -o test test.cpp -std=c++17 -Wall -Wextra
    - name: test_style
      run: ./test_style
    - name: test
      run: ./test
