name: CLANG CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt install -y clang curl
    - name: get doctest.h
      run: curl https://raw.githubusercontent.com/onqtam/doctest/v2.4.9/doctest/doctest.h > doctest.h
    - name: get version
      run: clang++ -v
    - name: compile style test
      run: clang++ -o test_style test/test_style.cpp -std=c++17 -Wall -Wextra
    - name: test style
      run: ./test_style
    - name: compile rectangle test
      run: clang++ -o test_rectangle test/test_rectangle.cpp -std=c++17 -Wall -Wextra
    - name: test rectangle
      run: ./test_rectangle
    - name: compile ellipse test
      run: clang++ -o test_ellipse test/test_ellipse.cpp -std=c++17 -Wall -Wextra
    - name: test ellipse
      run: ./test_ellipse
    - name: compile circle test
      run: clang++ -o test_circle test/test_circle.cpp -std=c++17 -Wall -Wextra
    - name: test circle
      run: ./test_circle
    - name: compile polyline test
      run: clang++ -o test_polyline test/test_polyline.cpp -std=c++17 -Wall -Wextra
    - name: test polyline
      run: ./test_polyline
    - name: compile polygon test
      run: clang++ -o test_polygon test/test_polygon.cpp -std=c++17 -Wall -Wextra
    - name: test polygon
      run: ./test_polygon
    - name: compile
      run: clang++ -o test.bin test/test.cpp -std=c++17 -Wall -Wextra
    - name: test
      run: ./test.bin
