name: CLANG CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt install -y clang curl
    - name: get doctest.h
      run: curl https://raw.githubusercontent.com/onqtam/doctest/v2.4.9/doctest/doctest.h > doctest.h
    - name: get version
      run: clang++ -v
    - name: compile style test
      run: clang++ -o test_style test/test_style.cpp -std=c++17 -Wall -Wextra
    - name: test style
      run: ./test_style
    - name: compile transform test
      run: clang++ -o test_transform test/test_transform.cpp -std=c++17 -Wall -Wextra
    - name: test transform
      run: ./test_transform
    - name: compile line test
      run: clang++ -o test_line test/test_line.cpp -std=c++17 -Wall -Wextra
    - name: test line
      run: ./test_line
    - name: compile rectangle test
      run: clang++ -o test_rectangle test/test_rectangle.cpp -std=c++17 -Wall -Wextra
    - name: test rectangle
      run: ./test_rectangle
    - name: compile ellipse test
      run: clang++ -o test_ellipse test/test_ellipse.cpp -std=c++17 -Wall -Wextra
    - name: test ellipse
      run: ./test_ellipse
    - name: compile circle test
      run: clang++ -o test_circle test/test_circle.cpp -std=c++17 -Wall -Wextra
    - name: test circle
      run: ./test_circle
    - name: compile polyline test
      run: clang++ -o test_polyline test/test_polyline.cpp -std=c++17 -Wall -Wextra
    - name: test polyline
      run: ./test_polyline
    - name: compile polygon test
      run: clang++ -o test_polygon test/test_polygon.cpp -std=c++17 -Wall -Wextra
    - name: test polygon
      run: ./test_polygon
    - name: compile text test
      run: clang++ -o test_text test/test_text.cpp -std=c++17 -Wall -Wextra
    - name: test text
      run: ./test_text
    - name: compile desc test
      run: clang++ -o test_desc test/test_desc.cpp -std=c++17 -Wall -Wextra
    - name: test desc
      run: ./test_desc
    - name: compile stop test
      run: clang++ -o test_stop test/test_stop.cpp -std=c++17 -Wall -Wextra
    - name: test stop
      run: ./test_stop
    - name: compile linearGradient test
      run: clang++ -o test_linearGradient test/test_linearGradient.cpp -std=c++17 -Wall -Wextra
    - name: test linearGradient
      run: ./test_linearGradient
    - name: compile radialGradient test
      run: clang++ -o test_radialGradient test/test_radialGradient.cpp -std=c++17 -Wall -Wextra
    - name: test radialGradient
      run: ./test_radialGradient
    - name: compile image test
      run: clang++ -o test_image test/test_image.cpp -std=c++17 -Wall -Wextra
    - name: test image
      run: ./test_image
    - name: compile group test
      run: clang++ -o test_group test/test_group.cpp -std=c++17 -Wall -Wextra
    - name: test group
      run: ./test_group
    - name: compile
      run: clang++ -o test.bin test/test.cpp -std=c++17 -Wall -Wextra
    - name: test
      run: ./test.bin
